version: '3.8'
services:
  fivly-mysql:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - "${MYSQL_PORT}:3306"
    volumes:
      - fivly-data:/var/lib/mysql
    restart: unless-stopped

  fivly-pma:
    image: phpmyadmin/phpmyadmin:latest
    ports:
      - "${PMA_PORT}:80"
    depends_on:
      - fivly-mysql
    environment:
      PMA_HOST: fivly-mysql

  fivly-minio:
    image: minio/minio
    container_name: fivly-minio
    environment:
      MINIO_ROOT_USER: ${MINIO_ROOT_USER}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}
      MINIO_BUCKET_NAME: ${MINIO_BUCKET_NAME}
    ports:
      - "${MINIO_FIRST_PORT}:9000"
      - "${MINIO_SECOND_PORT}:9001"
    volumes:
      - fivly-minio-data:/data
      - ./minio-start.sh:/usr/local/bin/minio-start.sh
    entrypoint: /bin/sh /usr/local/bin/minio-start.sh

volumes:
  fivly-data:
    driver: local
  fivly-minio-data:
    driver: local
