version: '3.8'
services:
  fivly-mysql:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - "${MYSQL_PORT}:3306"
    volumes:
      - fivly-data:/var/lib/mysql
    restart: unless-stopped

  fivly-pma:
    image: phpmyadmin/phpmyadmin:latest
    ports:
      - "${PMA_PORT}:80"
    depends_on:
      - fivly-mysql
    environment:
      PMA_HOST: fivly-mysql

volumes:
  fivly-data:
    driver: local
