version: '3.8'
services:
  fivly-api:
    build: .
    ports:
      - "${API_PORT}:3000"
    volumes:
      - .:/app
    depends_on:
      - fivly-mysql
    environment:
      - MYSQL_HOST=fivly-mysql
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
    networks:
      - fivly-network
      - proxiable
    restart: unless-stopped

  fivly-mysql:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - fivly-data:/var/lib/mysql
    networks:
      - fivly-network
    restart: unless-stopped

  fivly-pma:
    image: phpmyadmin/phpmyadmin:latest
    ports:
      - "${PMA_PORT}:80"
    depends_on:
      - fivly-mysql
    environment:
      PMA_HOST: fivly-mysql
    networks:
      - fivly-network
      - proxiable

volumes:
  fivly-data:
    driver: local

networks:
  fivly-network:
  proxiable:
    external: true